[2025-04-06T02:25:41.528+0000] {processor.py:186} INFO - Started process (PID=3804) to work on /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-06T02:25:41.529+0000] {processor.py:914} INFO - Processing file /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-06T02:25:41.531+0000] {logging_mixin.py:190} INFO - [2025-04-06T02:25:41.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-06T02:25:41.534+0000] {logging_mixin.py:190} INFO - [2025-04-06T02:25:41.534+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-06T02:25:41.535+0000] {logging_mixin.py:190} INFO - [2025-04-06T02:25:41.534+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-06T02:25:41.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-06T02:25:41.545+0000] {processor.py:208} INFO - Processing /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-04-06T02:26:47.178+0000] {processor.py:186} INFO - Started process (PID=3875) to work on /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-06T02:26:47.180+0000] {processor.py:914} INFO - Processing file /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-06T02:26:47.181+0000] {logging_mixin.py:190} INFO - [2025-04-06T02:26:47.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-06T02:26:47.185+0000] {logging_mixin.py:190} INFO - [2025-04-06T02:26:47.184+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-06T02:26:47.185+0000] {logging_mixin.py:190} INFO - [2025-04-06T02:26:47.185+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-06T02:26:47.186+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-06T02:26:47.195+0000] {processor.py:208} INFO - Processing /home/ubuntu/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
